# Documentation
# https://github.com/docker/metadata-action
# https://github.com/docker/login-action#google-container-registry-gcr
# https://github.com/docker/build-push-action
name: Push to GCR GitHub Action
on: 
  push:
    branches:
      - '**'   #Arnaud: We should probably build the docker container only after a PR is merged to main or a tagged is pushed
    tags:
      - '**'

jobs:
  check-env:
    runs-on: ubuntu-latest
    # assign output from step to job output
    outputs:
      gcloud-service-key: ${{ steps.gcloud-service-key.outputs.defined }}
    steps:
      - id: -segcloudrvice-key
        # assign GCLOUD_SERVICE_KEY to env for access in conditional
        env:
          GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
        if: "${{ env.GCLOUD_SERVICE_KEY != '' }}"
        # runs if GCLOUD_SERVICE_KEY is defined, so we set the output to true
        run: echo "::set-output name=defined::true"

  build-and-push-to-gcr:
    runs-on: ubuntu-latest

    # uses check-env to determine if secrets.GCLOUD_SERVICE_KEY is defined
    needs: [check-env]
    if: needs.check-env.outputs.gcloud-service-key == 'true'

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
      - uses: Swatinem/rust-cache@v1
        with:
          key: 'release' # Added extra key to prevent rust cache collision with rust.yml workflows
      
      - name: Build agents (release)
        run: cargo build --release

      - name: Login to Docker repository
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCLOUD_SERVICE_KEY }}

      - name: Build and push container
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
